---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# HIEdroughtbox

<!-- badges: start -->
<!-- badges: end -->

The goal of HIEdroughtbox is to ...

## Installation

You can install the development version of HIEdroughtbox from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("ecamo19/hie_dRoughtbox")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r libraries, message = FALSE,warning = FALSE}
library(HIEdroughtbox)
library(dplyr)
```

### Read droughtbox data

```{r example}
data <- read_hie_droughtbox_data("data/acacia_aneura_25c.dat")
head(data)
```


### Visualize climatic conditions

```{r example_plot_climatic_controls, fig.height=30, fig.width=35}
plot_droughtbox_climatic_controls(data, cowplot = T)
```

### Visualize __raw__ weights measured by the strains

```{r example_plot_raw_weights, fig.height=10, fig.width=15}
plot_raw_strains_weights(data)
```

